[[MuJoCo]]
arch = "aarch64"
git-tree-sha1 = "a553abd5b834db00efdca44e2adb7bcb9c028bb9"
os = "macos"

    [[MuJoCo.download]]
    sha256 = "b9dd672d41234ca3c7c57d9ecdfc1d5e716c1975022254cc80f6dc40eaf5f205"
    url = "https://github.com/JuliaBinaryWrappers/MuJoCo_jll.jl/releases/download/MuJoCo-v3.1.6+0/MuJoCo.v3.1.6.aarch64-apple-darwin.tar.gz"
[[MuJoCo]]
arch = "aarch64"
git-tree-sha1 = "994c66a9960b40af5e7901ea475b502960530ca1"
libc = "glibc"
os = "linux"

    [[MuJoCo.download]]
    sha256 = "12408494e51f8ba784f626b93342a068c6a4a2701a15a378a2f0a4dc249b8e86"
    url = "https://github.com/JuliaBinaryWrappers/MuJoCo_jll.jl/releases/download/MuJoCo-v3.1.6+0/MuJoCo.v3.1.6.aarch64-linux-gnu.tar.gz"
[[MuJoCo]]
arch = "powerpc64le"
git-tree-sha1 = "8e016966e8d220b77d1f098365f4d0a27a0c7e6e"
libc = "glibc"
os = "linux"

    [[MuJoCo.download]]
    sha256 = "a6ef200c112fc8e61de8eab49781fac7aa7f3cf58c7fde1bd6219eed3cec5ec7"
    url = "https://github.com/JuliaBinaryWrappers/MuJoCo_jll.jl/releases/download/MuJoCo-v3.1.6+0/MuJoCo.v3.1.6.powerpc64le-linux-gnu.tar.gz"
[[MuJoCo]]
arch = "x86_64"
git-tree-sha1 = "c25c6b333f3b2025ac165e6b9d41fd3191327adc"
os = "macos"

    [[MuJoCo.download]]
    sha256 = "337aeaee8f54b6cd110dcad64dce71f076c7c94cf5d024f2a8c28e7c38bdc8d9"
    url = "https://github.com/JuliaBinaryWrappers/MuJoCo_jll.jl/releases/download/MuJoCo-v3.1.6+0/MuJoCo.v3.1.6.x86_64-apple-darwin.tar.gz"
[[MuJoCo]]
arch = "x86_64"
git-tree-sha1 = "3f32b16a6b9173280ee0d7e3d02926fd5da2e34b"
libc = "glibc"
os = "linux"

    [[MuJoCo.download]]
    sha256 = "93005daeb9ec116bb25d3f093a3552ec08efa4ad31c5efac2de76c3282175095"
    url = "https://github.com/JuliaBinaryWrappers/MuJoCo_jll.jl/releases/download/MuJoCo-v3.1.6+0/MuJoCo.v3.1.6.x86_64-linux-gnu.tar.gz"
[[MuJoCo]]
arch = "x86_64"
git-tree-sha1 = "a888d6da9450c3b100f471651ef90338e9a7ba7e"
os = "windows"

    [[MuJoCo.download]]
    sha256 = "36e2431b7118c861c860923dead3c03b6b519422793dd0732d2451c7e9fd642e"
    url = "https://github.com/JuliaBinaryWrappers/MuJoCo_jll.jl/releases/download/MuJoCo-v3.1.6+0/MuJoCo.v3.1.6.x86_64-w64-mingw32.tar.gz"
